#! /bin/sh

echo "--- This is the bootstrap script for libsc calling autoreconf ---"
echo "It is NOT required to run bootstrap to build from a tar.gz archive"
echo "Current directory is $PWD"

rm -rf autom4te.cache
autoreconf -i
