#! /bin/sh

MODULES="
   base64
   getopt
   obstack
   stdint
   stdlib
   string
   calloc-posix
   malloc-posix
"
AVOIDED="
   exit
   exitfail
"
#   fpieee
#   isnand-nolibm
#   isnanf-nolibm
#   isnanl-nolibm

GNULIB_FLAGS=
case "$1" in
    --import)
	rm -rf gnulib
	;;
    --dryrun)
	GNULIB_FLAGS="$GBULIB_FLAGS --dry-run"
	;;
    --show)
	echo -n "GNUlib modules selected by sclib: $MODULES"
	echo -n "GNUlib modules excluded by sclib: $AVOIDED"
	exit 0
	;;
    *)
	echo "Usage: ./scgnulib (--show | --dryrun | --import)"
	exit 0
	;;
esac

AVOIDLIST=
for AVOID in $AVOIDED ; do
  AVOIDLIST="$AVOIDLIST --avoid=$AVOID"
done

gnulib-tool $GNULIB_FLAGS --lgpl=3 $AVOIDLIST \
    --source-base=gnulib --m4-base=gnulib/m4 \
    --doc-base=gnulib/doc --tests-base=gnulib/test \
    --macro-prefix=GNULIB --import $MODULES
