name: CI for testing cmake build on autotools tarball

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.cmake.in"
      - "**.c"
      - "**.h"
      - "**.h.in"
      - ".github/workflows/ci_autotools_tarball.yml"
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    name: autotools build on Linux
    timeout-minutes: 15

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            zlib1g-dev libmpich-dev mpich

    - uses: actions/checkout@v2
      name: Checkout source code

    - name: Autotools build
      run: |
          ./bootstrap
          DIR="checkMPIdebug_shared" && mkdir -p "$DIR" && cd "$DIR"
          ../configure --enable-mpi --enable-debug --disable-shared \
              CFLAGS="-O0 -g -Wall -Wextra -Wno-unused-parameter"
          make -j check V=0
