name: CI for testing cmake build on autotools tarball

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.cmake.in"
      - "**.c"
      - "**.h"
      - "**.h.in"
      - ".github/workflows/ci_autotools_tarball.yml"
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    name: autotools build on Linux
    timeout-minutes: 15

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            zlib1g-dev libmpich-dev mpich

    - uses: actions/checkout@v2
      name: Checkout source code

    - name: Autotools build
      shell: bash
      run: |
          ./bootstrap
          DIR="autotools_build" && mkdir -p "$DIR" && cd "$DIR"
          ../configure --enable-mpi --enable-debug --disable-shared \
              CFLAGS="-O0 -g -Wall -Wextra -Wno-unused-parameter"
          make -j check V=0

    - name: Pack autotools tarball
      shell: bash
      run: |
          ../configure --enable-mpi --enable-debug --disable-shared \
              CFLAGS="-O0 -g -Wall -Wextra -Wno-unused-parameter"s
          make -j distcheck V=0

    - name: CMake build
      shell: bash
      run: |
          TARBALL=$(find . -maxdepth 1 -name "*.tar.gz")
          CMAKE_DIR="check_cmake" && mkdir -p "$CMAKE_DIR" && cd "$CMAKE_DIR"
          tar -xvzf ../$TARBALL
          EXTRACT=${TARBALL/%.tar.gz}
          PATH_TO_SOURCE="$PWD/$EXTRACT"
          CMAKE_BUILD_DIR="cmake_build" && mkdir -p "$CMAKE_BUILD_DIR" && cd "$CMAKE_BUILD_DIR"
          cmake PATH_TO_SOURCE
          cmake --build .