name: CI for testing autotools build on CMake tarball

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.cmake.in"
      - "**.c"
      - "**.h"
      - "**.h.in"
      - ".github/workflows/ci_cmake_tarball.yml"
  pull_request:
  release:
    types: [published]

jobs:

  linux:
    runs-on: ubuntu-latest
    name: CMake build on Linux
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            libopenmpi-dev openmpi-bin

    - name: CMake configure and build
      shell: bash
      run: |
        DIR="cmake_build" && mkdir -p "$DIR" && cd "$DIR"
        cmake ..
        cmake --build .
        cpack --config CPackSourceConfig.cmake
        cd ./package
        TARBALL=$(find . -maxdepth 1 -name "*.tar.gz")
        tar -xzf $TARBALL
        EXTRACT=${TARBALL/%.tar.gz}
        cd $EXTRACT
        ./bootstrap
        ./configure --enable-mpi --enable-debug --disable-shared CFLAGS="-O0 -g -Wall -Wextra -Wno-unused-parameter"
        make check -j10 V=0
        make distcheck -j10 V=0

        